// ios_app_of_blog/src/pages/login/index.vue
<template>
  <view class="login-page">
    <view class="login-card">
      <text class="login-title">管理员登录</text>
      <text class="login-subtitle">登录后可发布、编辑和删除文章</text>

      <view class="form-group">
        <text class="form-label">用户名</text>
        <input
          class="form-input"
          type="text"
          placeholder="请输入用户名"
          v-model="username"
        />
      </view>

      <view class="form-group">
        <text class="form-label">密码</text>
        <input
          class="form-input"
          type="password"
          placeholder="请输入密码"
          v-model="password"
          @confirm="doLogin"
        />
      </view>

      <view class="login-btn" :class="{ disabled: submitting }" @click="doLogin">
        <text class="login-btn-text">{{ submitting ? '登录中...' : '登录' }}</text>
      </view>

      <view class="login-error" v-if="errorMsg">
        <text class="error-text">{{ errorMsg }}</text>
      </view>
    </view>
  </view>
</template>

<script>
import { login } from '../../services/api'
import { saveAuth, isLoggedIn } from '../../utils/auth'

export default {
  data() {
    return {
      username: '',
      password: '',
      submitting: false,
      errorMsg: ''
    }
  },
  onShow() {
    if (isLoggedIn()) {
      uni.navigateBack({ fail: () => uni.reLaunch({ url: '/pages/index/index' }) })
    }
  },
  methods: {
    async doLogin() {
      if (this.submitting) return
      if (!this.username.trim() || !this.password.trim()) {
        this.errorMsg = '请输入用户名和密码'
        return
      }
      this.submitting = true
      this.errorMsg = ''
      try {
        const res = await login(this.username, this.password)
        if (res.code === 200 && res.data?.token) {
          saveAuth(res.data.token, res.data.username || this.username)
          uni.showToast({ title: '登录成功', icon: 'success' })
          setTimeout(() => {
            uni.navigateBack({ fail: () => uni.reLaunch({ url: '/pages/index/index' }) })
          }, 1500)
        } else {
          this.errorMsg = res.msg || '登录失败'
        }
      } catch (e) {
        this.errorMsg = '网络错误，请稍后重试'
      } finally {
        this.submitting = false
      }
    }
  }
}
</script>

<style scoped>
.login-page {
  padding: 80rpx 32rpx;
  min-height: 100vh;
  background-color: #fafafa;
}

.login-card {
  background-color: #ffffff;
  border-radius: 24rpx;
  padding: 48rpx 40rpx;
  box-shadow: 0 2rpx 12rpx rgba(0, 0, 0, 0.04);
  border: 1rpx solid #f0f0f0;
}

.login-title {
  font-size: 40rpx;
  font-weight: 700;
  color: #1a1a1a;
  margin-bottom: 12rpx;
  display: block;
}

.login-subtitle {
  font-size: 26rpx;
  color: #999;
  margin-bottom: 48rpx;
  display: block;
}

.form-group {
  margin-bottom: 32rpx;
}

.form-label {
  font-size: 26rpx;
  font-weight: 500;
  color: #374151;
  margin-bottom: 12rpx;
  display: block;
}

.form-input {
  width: 100%;
  height: 88rpx;
  background-color: #fafafa;
  border: 1rpx solid #e5e7eb;
  border-radius: 16rpx;
  padding: 0 24rpx;
  font-size: 28rpx;
  color: #1a1a1a;
  box-sizing: border-box;
}

.login-btn {
  width: 100%;
  height: 96rpx;
  background-color: #2563eb;
  border-radius: 16rpx;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-top: 16rpx;
}

.login-btn:active {
  opacity: 0.85;
}

.login-btn.disabled {
  opacity: 0.6;
}

.login-btn-text {
  color: #ffffff;
  font-size: 30rpx;
  font-weight: 600;
}

.login-error {
  margin-top: 24rpx;
  padding: 16rpx 24rpx;
  background-color: #fef2f2;
  border-radius: 12rpx;
}

.error-text {
  font-size: 26rpx;
  color: #dc2626;
}
</style>

// front_end_of_blog/src/pages/Login.jsx
/**
 * 管理员登录页
 * 简洁的账号密码登录表单
 */
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { login } from '../services/api';
import { setAuth, isLoggedIn } from '../utils/auth';
import './Login.css';

function Login() {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    username: '',
    password: ''
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    if (isLoggedIn()) {
      navigate('/');
    }
  }, [navigate]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
    setError('');
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!formData.username.trim() || !formData.password.trim()) {
      setError('请输入用户名和密码');
      return;
    }

    try {
      setLoading(true);
      setError('');
      
      const res = await login(formData.username, formData.password);
      
      if (res.code === 200) {
        setAuth(res.data.token, res.data.username);
        navigate('/');
        window.location.reload();
      } else {
        setError(res.msg || '登录失败');
      }
    } catch (err) {
      setError(err.msg || '网络错误，请稍后重试');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="login-page">
      <div className="login-container card">
        <h1 className="login-title">管理员登录</h1>
        <p className="login-subtitle">登录后可发布和管理文章</p>

        <form className="login-form" onSubmit={handleSubmit}>
          {error && (
            <div className="message message-error">{error}</div>
          )}

          <div className="form-group">
            <label htmlFor="username" className="form-label">用户名</label>
            <input
              type="text"
              id="username"
              name="username"
              className="input"
              value={formData.username}
              onChange={handleChange}
              placeholder="请输入用户名"
              autoComplete="username"
            />
          </div>

          <div className="form-group">
            <label htmlFor="password" className="form-label">密码</label>
            <input
              type="password"
              id="password"
              name="password"
              className="input"
              value={formData.password}
              onChange={handleChange}
              placeholder="请输入密码"
              autoComplete="current-password"
            />
          </div>

          <button 
            type="submit" 
            className="btn btn-primary login-btn"
            disabled={loading}
          >
            {loading ? '登录中...' : '登录'}
          </button>
        </form>
      </div>
    </div>
  );
}

export default Login;
